using ProPlusBot.Entities;

namespace ProPlusBot.Services.Subscriptions;

public static class SubscriptionSeedData
{
    public static IReadOnlyList<PlanPricing> DefaultPlanDefinitions() =>
    [
        Plan(SubscriptionPlan.Free,
            price: 0,
            downloads: 60,
            downloadMb: 1000,
            searches: 40,
            tickets: 2,
            maxFileMb: 25,
            extraCountPrice: 15_000,
            extraCountPack: 5,
            extraBytesPrice: 15_000,
            extraBytesMb: 200,
            fallbackSize: false,
            fallbackFail: false,
            fallbackExpiryHours: 24),
        Plan(SubscriptionPlan.Bronze,
            price: 99_000,
            downloads: 300,
            downloadMb: 4096,
            searches: 400,
            tickets: 5,
            maxFileMb: 40,
            extraCountPrice: 25_000,
            extraCountPack: 10,
            extraBytesPrice: 25_000,
            extraBytesMb: 500,
            fallbackSize: false,
            fallbackFail: true,
            fallbackExpiryHours: 24),
        Plan(SubscriptionPlan.Silver,
            price: 199_000,
            downloads: 800,
            downloadMb: 10240,
            searches: 1000,
            tickets: 10,
            maxFileMb: 49,
            extraCountPrice: 35_000,
            extraCountPack: 15,
            extraBytesPrice: 35_000,
            extraBytesMb: 1024,
            fallbackSize: true,
            fallbackFail: true,
            fallbackExpiryHours: 24),
        Plan(SubscriptionPlan.Golden,
            price: 399_000,
            downloads: 2000,
            downloadMb: 30720,
            searches: 4000,
            tickets: 20,
            maxFileMb: 250,
            extraCountPrice: 49_000,
            extraCountPack: 25,
            extraBytesPrice: 49_000,
            extraBytesMb: 2048,
            fallbackSize: true,
            fallbackFail: true,
            fallbackExpiryHours: 24),
    ];

    private static PlanPricing Plan(
        SubscriptionPlan plan,
        long price,
        long downloads,
        int downloadMb,
        long searches,
        int tickets,
        int maxFileMb,
        long extraCountPrice,
        int extraCountPack,
        long extraBytesPrice,
        int extraBytesMb,
        bool fallbackSize,
        bool fallbackFail,
        int fallbackExpiryHours) =>
        new()
        {
            Plan = plan,
            MonthlyPriceToman = price,
            MonthlyDownloadCount = downloads,
            MonthlyDownloadBytes = downloadMb * 1024L * 1024,
            MonthlySearchCount = searches,
            MonthlyTicketLimit = tickets,
            MaxFileBytes = maxFileMb * 1024L * 1024,
            ExtraDownloadCountPriceToman = extraCountPrice,
            ExtraDownloadCountPack = extraCountPack,
            ExtraDownloadBytesPriceToman = extraBytesPrice,
            ExtraDownloadBytesPack = extraBytesMb * 1024L * 1024,
            FallbackOnSizeExceed = fallbackSize,
            FallbackOnBaleFailure = fallbackFail,
            FallbackLinkExpiryHours = fallbackExpiryHours,
            UpdatedAt = DateTime.UtcNow
        };
}
