// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProPlusBot.Data;

#nullable disable

namespace ProPlusBot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524003556_ConsolidatePlanQuotas")]
    partial class ConsolidatePlanQuotas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProPlusBot.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("ProPlusBot.Entities.BotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationStateBackend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<bool>("PinterestEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SearchGridColumns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("SearchGridJpegQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(85);

                    b.Property<int>("SearchGridRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("UpdateMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("YouTubeCookiesContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("YouTubeCookiesUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("YouTubeEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("ProPlusBot.Entities.BotUser", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("HasJoinedChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSharedPhone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QuotaPeriodStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedRole")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TelegramUserId");

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("ProPlusBot.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ProPlusBot.Entities.DownloadUsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "CreatedAt");

                    b.HasIndex("TelegramUserId", "Platform", "CreatedAt");

                    b.ToTable("DownloadUsageLogs");
                });

            modelBuilder.Entity("ProPlusBot.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Service")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ProPlusBot.Entities.MediaDownloadJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("IncomingChatMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("YouTubeFormatId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IncomingChatMessageId");

                    b.HasIndex("Status");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("MediaDownloadJobs", (string)null);
                });

            modelBuilder.Entity("ProPlusBot.Entities.OtpSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("OtpSessions");
                });

            modelBuilder.Entity("ProPlusBot.Entities.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountRials")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountToman")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("FromPlan")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPaymentChargeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderTelegramPaymentChargeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ToPlan")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("ProPlusBot.Entities.PlanPricing", b =>
                {
                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<long>("ExtraDownloadBytesPack")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtraDownloadBytesPriceToman")
                        .HasColumnType("bigint");

                    b.Property<int>("ExtraDownloadCountPack")
                        .HasColumnType("integer");

                    b.Property<long>("ExtraDownloadCountPriceToman")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxFileBytesPinterest")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxFileBytesYouTube")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyDownloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyDownloadCount")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyPriceToman")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlySearchCount")
                        .HasColumnType("bigint");

                    b.Property<int>("MonthlyTicketLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Plan");

                    b.ToTable("PlanPricings");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SearchUsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "Platform", "CreatedAt");

                    b.ToTable("SearchUsageLogs");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAdminReplyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TelegramUserId", "Status");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SupportTicketMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IncomingChatMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sender")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TicketId");

                    b.ToTable("SupportTicketMessages");
                });

            modelBuilder.Entity("ProPlusBot.Entities.TrialSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TrialSettings");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserInteractionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IncomingChatMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaDownloadJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IncomingChatMessageId");

                    b.HasIndex("MediaDownloadJobId");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("UserInteractionLogs");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserPlanPlatformLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LimitKind")
                        .HasColumnType("integer");

                    b.Property<long>("LimitValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "Platform", "Period", "LimitKind")
                        .IsUnique();

                    b.ToTable("UserPlanPlatformLimits");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserQuotaAdjustment", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtraDownloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ExtraDownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TelegramUserId");

                    b.ToTable("UserQuotaAdjustments");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserReservedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "CreatedAt");

                    b.ToTable("UserReservedPlans");
                });

            modelBuilder.Entity("ProPlusBot.Entities.ChatMessage", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.DownloadUsageLog", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("DownloadUsages")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.MediaDownloadJobEntity", b =>
                {
                    b.HasOne("ProPlusBot.Entities.ChatMessage", "IncomingChatMessage")
                        .WithMany()
                        .HasForeignKey("IncomingChatMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingChatMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.PaymentRecord", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SearchUsageLog", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("SearchUsages")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SupportTicket", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SupportTicketMessage", b =>
                {
                    b.HasOne("ProPlusBot.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProPlusBot.Entities.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserInteractionLog", b =>
                {
                    b.HasOne("ProPlusBot.Entities.ChatMessage", "IncomingChatMessage")
                        .WithMany()
                        .HasForeignKey("IncomingChatMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProPlusBot.Entities.MediaDownloadJobEntity", "MediaDownloadJob")
                        .WithMany()
                        .HasForeignKey("MediaDownloadJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingChatMessage");

                    b.Navigation("MediaDownloadJob");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserPlanPlatformLimit", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("PlanPlatformLimits")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserQuotaAdjustment", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("QuotaAdjustments")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.UserReservedPlan", b =>
                {
                    b.HasOne("ProPlusBot.Entities.BotUser", "User")
                        .WithMany("ReservedPlans")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPlusBot.Entities.BotUser", b =>
                {
                    b.Navigation("DownloadUsages");

                    b.Navigation("Messages");

                    b.Navigation("Payments");

                    b.Navigation("PlanPlatformLimits");

                    b.Navigation("QuotaAdjustments");

                    b.Navigation("ReservedPlans");

                    b.Navigation("SearchUsages");
                });

            modelBuilder.Entity("ProPlusBot.Entities.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
